sudo: required

language: cpp

compiler:
  - gcc
  - clang

dist: trusty

arch:
  packages:
    - cmake
    - gcc
    - gtest
  script:
    - "mkdir build"
    - "cd build"
    - "cmake ../"
    - "make -j4"
    - "make test"

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

branches:
  only:
    - master
notifications:
  recipients:
    - zwkno1@gmail.com
  email:
    on_success: change
    on_failure: always
